export const multichainRpc = {
  56: [
    "https://bsc-dataseed.binance.org/",
    "https://bsc-dataseed1.ninicoin.io",
    "https://bsc-dataseed2.ninicoin.io",
    "https://bsc-dataseed3.ninicoin.io",
    "https://bsc-dataseed1.defibit.io",
    "https://bsc-dataseed2.defibit.io",
    "https://bsc-dataseed3.defibit.io",
    "https://rpc.ankr.com/bsc",
    "https://bsc-dataseed1.binance.org/",
    "https://bsc-dataseed2.binance.org/",
    "https://bsc-dataseed3.binance.org/",
    "https://bsc-dataseed4.binance.org/",
  ],
  1: [
    "https://ethereum.publicnode.com",
    "https://eth.llamarpc.com",
    "https://rpc.mevblocker.io",
    "https://eth-mainnet.public.blastapi.io",
    "https://api.securerpc.com/v1",
    "https://1rpc.io/eth",
    "https://rpc.builder0x69.io",
    "https://eth-rpc.gateway.pokt.network",
    "https://rpc.ankr.com/eth",
    "https://cloudflare-eth.com",
    "https://1rpc.io/eth",
    "https://rpc.payload.de",
  ],
  137: [
    "https://polygon-rpc.com",
    "https://polygon-mainnet.g.alchemy.com/v2/demo",
    "https://rpc-mainnet.matic.quiknode.pro",
    "https://polygon.llamarpc.com",
    "https://poly-rpc.gateway.pokt.network",
    "https://polygon.llamarpc.com",
    "https://rpc-mainnet.maticvigil.com",
    "https://rpc-mainnet.matic.network",
  ],
  43114: [
    "https://api.avax.network/ext/bc/C/rpc",
    "https://1rpc.io/avax/c",
    "https://avalanche-c-chain.publicnode.com",
    "https://rpc.ankr.com/avalanche",
    "https://avalanche-c-chain.publicnode.com",
    "https://endpoints.omniatech.io/v1/avax/mainnet/public",
    "https://avalanche.blockpi.network/v1/rpc/public",
  ],
  42161: [
    "https://arb1.croswap.com/rpc",
    "https://rpc.ankr.com/arbitrum",
    "https://arb-mainnet-public.unifra.io",
    "https://endpoints.omniatech.io/v1/arbitrum/one/public",
    "https://arbitrum.blockpi.network/v1/rpc/public",
    "https://arbitrum.blockpi.network/v1/rpc/public",
  ],
  80001: [
    "https://polygon-mumbai.g.alchemy.com/v2/0ORsvD9y8x1JBZJ1lIlNU_-8ILbUSkuF",
    "https://matic-mumbai.chainstacklabs.com",
    "https://polygon-mumbai.blockpi.network/v1/rpc/public",
    "https://polygon-testnet.public.blastapi.io",
    "https://endpoints.omniatech.io/v1/matic/mumbai/public",
    "https://matic-testnet-archive-rpc.bwarelabs.com/",
    "https://rpc-mumbai.maticvigil.com/",
    "https://rpc-mumbai.matic.today/",
  ],
  97: [
    "https://data-seed-prebsc-1-s1.binance.org:8545",
    "https://data-seed-prebsc-2-s1.binance.org:8545",
    "https://data-seed-prebsc-1-s2.binance.org:8545",
    "https://data-seed-prebsc-2-s2.binance.org:8545",
    "https://data-seed-prebsc-1-s3.binance.org:8545",
    "https://data-seed-prebsc-2-s3.binance.org:8545",
  ],
  11155111: [
    "https://eth-sepolia.g.alchemy.com/v2/587rhpE56Yqjv4384ZR3evg1JZ0h8fiX",
    "https://eth-sepolia.g.alchemy.com/v2/587rhpE56Yqjv4384ZR3evg1JZ0h8fiX",
    "https://eth-sepolia.g.alchemy.com/v2/587rhpE56Yqjv4384ZR3evg1JZ0h8fiX",
    "https://eth-sepolia.g.alchemy.com/v2/587rhpE56Yqjv4384ZR3evg1JZ0h8fiX",
    "https://eth-sepolia.g.alchemy.com/v2/587rhpE56Yqjv4384ZR3evg1JZ0h8fiX",
    "https://eth-sepolia.g.alchemy.com/v2/587rhpE56Yqjv4384ZR3evg1JZ0h8fiX",
    "https://rpc2.sepolia.org",
    "https://rpc.sepolia.org",
    "https://eth-sepolia.public.blastapi.io",
    "https://api.zan.top/node/v1/eth/sepolia/public",
    "https://rpc.notadegen.com/eth/sepolia",
    "https://ethereum-sepolia.blockpi.network/v1/rpc/public",
  ],
  undefined: [
    "https://data-seed-prebsc-1-s1.binance.org:8545",
    "https://data-seed-prebsc-2-s1.binance.org:8545",
    "https://data-seed-prebsc-1-s2.binance.org:8545",
    "https://data-seed-prebsc-2-s2.binance.org:8545",
    "https://data-seed-prebsc-1-s3.binance.org:8545",
    "https://data-seed-prebsc-2-s3.binance.org:8545",
  ],
};
